default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV['POSTGRES_DEVELOPMENT_DATABASE'] %>

test:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV['POSTGRES_TEST_DATABASE'] %>

production:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV['POSTGRES_PRODUCTION_DATABASE'] %>
  username: <%= ENV['POSTGRES_PRODUCTION_USER'] %>
  password: <%= ENV['POSTGRES_PRODUCTION_PASSWORD'] %>
